config/routes.rb
Rails.application.routes.draw do
  resources :horarios
  resources :alumno_asignaturas
  resources :salas
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :profesor, optional: true
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  before_action :set_asignatura, only: [:show, :edit, :update, :destroy]

  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.all
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
  end

  # GET /asignaturas/1/edit
  def edit
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully created.' }
        format.json { render :show, status: :created, location: @asignatura }
      else
        format.html { render :new }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaturas/1
  # PATCH/PUT /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully updated.' }
        format.json { render :show, status: :ok, location: @asignatura }
      else
        format.html { render :edit }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: 'Asignatura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:nombre, :credito, :profesor_id)
    end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_form.html.erb
<%= form_with(model: asignatura, local: true) do |form| %>
  <% if asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asignatura.errors.count, "error") %> prohibited this asignatura from being saved:</h2>

      <ul>
      <% asignatura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :credito %>
    <%= form.number_field :credito %>
  </div>

  <div class="field">
    <%= form.label :profesor_id %>
    <%= form.text_field :profesor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/asignaturas/edit.html.erb
<h1>Editing Asignatura</h1>

<%= render 'form', asignatura: @asignatura %>

<%= link_to 'Show', @asignatura %> |
<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asignaturas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Credito</th>
      <th>Profesor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asignaturas.each do |asignatura| %>
      <tr>
        <td><%= asignatura.nombre %></td>
        <td><%= asignatura.credito %></td>
        <td><%= asignatura.profesor %></td>
        <td><%= link_to 'Show', asignatura %></td>
        <td><%= link_to 'Edit', edit_asignatura_path(asignatura) %></td>
        <td><%= link_to 'Destroy', asignatura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asignatura', new_asignatura_path %>

app/views/asignaturas/new.html.erb
<h1>New Asignatura</h1>

<%= render 'form', asignatura: @asignatura %>

<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @asignatura.nombre %>
</p>

<p>
  <strong>Credito:</strong>
  <%= @asignatura.credito %>
</p>

<p>
  <strong>Profesor:</strong>
  <%= @asignatura.profesor %>
</p>

<%= link_to 'Edit', edit_asignatura_path(@asignatura) %> |
<%= link_to 'Back', asignaturas_path %>