config/routes.rb
Rails.application.routes.draw do
  resources :horarios
  resources :alumno_asignaturas
  resources :salas
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  belongs_to :usuario
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:titulo, :usuario_id)
    end
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/views/profesors/_form.html.erb
<%= form_with(model: profesor, local: true) do |form| %>
  <% if profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profesors/edit.html.erb
<h1>Editing Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesors_path %>

app/views/profesors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profesors</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
        <td><%= profesor.titulo %></td>
        <td><%= profesor.usuario %></td>
        <td><%= link_to 'Show', profesor %></td>
        <td><%= link_to 'Edit', edit_profesor_path(profesor) %></td>
        <td><%= link_to 'Destroy', profesor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profesor', new_profesor_path %>

app/views/profesors/new.html.erb
<h1>New Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Back', profesors_path %>

app/views/profesors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @profesor.titulo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @profesor.usuario %>
</p>

<%= link_to 'Edit', edit_profesor_path(@profesor) %> |
<%= link_to 'Back', profesors_path %>