config/routes.rb
Rails.application.routes.draw do
  resources :horarios
  resources :alumno_asignaturas
  resources :salas
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alumno_asignatura.rb
class AlumnoAsignatura < ApplicationRecord
  belongs_to :asignatura
  belongs_to :alumno
end

app/controllers/alumno_asignaturas_controller.rb
class AlumnoAsignaturasController < ApplicationController
  before_action :set_alumno_asignatura, only: [:show, :edit, :update, :destroy]

  # GET /alumno_asignaturas
  # GET /alumno_asignaturas.json
  def index
    @alumno_asignaturas = AlumnoAsignatura.all
  end

  # GET /alumno_asignaturas/1
  # GET /alumno_asignaturas/1.json
  def show
  end

  # GET /alumno_asignaturas/new
  def new
    @alumno_asignatura = AlumnoAsignatura.new
  end

  # GET /alumno_asignaturas/1/edit
  def edit
  end

  # POST /alumno_asignaturas
  # POST /alumno_asignaturas.json
  def create
    @alumno_asignatura = AlumnoAsignatura.new(alumno_asignatura_params)

    respond_to do |format|
      if @alumno_asignatura.save
        format.html { redirect_to @alumno_asignatura, notice: 'Alumno asignatura was successfully created.' }
        format.json { render :show, status: :created, location: @alumno_asignatura }
      else
        format.html { render :new }
        format.json { render json: @alumno_asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumno_asignaturas/1
  # PATCH/PUT /alumno_asignaturas/1.json
  def update
    respond_to do |format|
      if @alumno_asignatura.update(alumno_asignatura_params)
        format.html { redirect_to @alumno_asignatura, notice: 'Alumno asignatura was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno_asignatura }
      else
        format.html { render :edit }
        format.json { render json: @alumno_asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumno_asignaturas/1
  # DELETE /alumno_asignaturas/1.json
  def destroy
    @alumno_asignatura.destroy
    respond_to do |format|
      format.html { redirect_to alumno_asignaturas_url, notice: 'Alumno asignatura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno_asignatura
      @alumno_asignatura = AlumnoAsignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_asignatura_params
      params.require(:alumno_asignatura).permit(:nota, :ponderacion, :fecha_publicacion, :asignatura_id, :alumno_id)
    end
end

app/helpers/alumno_asignaturas_helper.rb
module AlumnoAsignaturasHelper
end

app/views/alumno_asignaturas/_form.html.erb
<%= form_with(model: alumno_asignatura, local: true) do |form| %>
  <% if alumno_asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumno_asignatura.errors.count, "error") %> prohibited this alumno_asignatura from being saved:</h2>

      <ul>
      <% alumno_asignatura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nota %>
    <%= form.text_field :nota %>
  </div>

  <div class="field">
    <%= form.label :ponderacion %>
    <%= form.text_field :ponderacion %>
  </div>

  <div class="field">
    <%= form.label :fecha_publicacion %>
    <%= form.date_select :fecha_publicacion %>
  </div>

  <div class="field">
    <%= form.label :asignatura_id %>
    <%= form.text_field :asignatura_id %>
  </div>

  <div class="field">
    <%= form.label :alumno_id %>
    <%= form.text_field :alumno_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alumno_asignaturas/edit.html.erb
<h1>Editing Alumno Asignatura</h1>

<%= render 'form', alumno_asignatura: @alumno_asignatura %>

<%= link_to 'Show', @alumno_asignatura %> |
<%= link_to 'Back', alumno_asignaturas_path %>

app/views/alumno_asignaturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumno Asignaturas</h1>

<table>
  <thead>
    <tr>
      <th>Nota</th>
      <th>Ponderacion</th>
      <th>Fecha publicacion</th>
      <th>Asignatura</th>
      <th>Alumno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumno_asignaturas.each do |alumno_asignatura| %>
      <tr>
        <td><%= alumno_asignatura.nota %></td>
        <td><%= alumno_asignatura.ponderacion %></td>
        <td><%= alumno_asignatura.fecha_publicacion %></td>
        <td><%= alumno_asignatura.asignatura %></td>
        <td><%= alumno_asignatura.alumno %></td>
        <td><%= link_to 'Show', alumno_asignatura %></td>
        <td><%= link_to 'Edit', edit_alumno_asignatura_path(alumno_asignatura) %></td>
        <td><%= link_to 'Destroy', alumno_asignatura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno Asignatura', new_alumno_asignatura_path %>

app/views/alumno_asignaturas/new.html.erb
<h1>New Alumno Asignatura</h1>

<%= render 'form', alumno_asignatura: @alumno_asignatura %>

<%= link_to 'Back', alumno_asignaturas_path %>

app/views/alumno_asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nota:</strong>
  <%= @alumno_asignatura.nota %>
</p>

<p>
  <strong>Ponderacion:</strong>
  <%= @alumno_asignatura.ponderacion %>
</p>

<p>
  <strong>Fecha publicacion:</strong>
  <%= @alumno_asignatura.fecha_publicacion %>
</p>

<p>
  <strong>Asignatura:</strong>
  <%= @alumno_asignatura.asignatura %>
</p>

<p>
  <strong>Alumno:</strong>
  <%= @alumno_asignatura.alumno %>
</p>

<%= link_to 'Edit', edit_alumno_asignatura_path(@alumno_asignatura) %> |
<%= link_to 'Back', alumno_asignaturas_path %>