config/routes.rb
Rails.application.routes.draw do
  resources :horarios
  resources :alumno_asignaturas
  resources :salas
  resources :asignaturas
  resources :alumnos
  resources :profesors
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sala.rb
class Sala < ApplicationRecord
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  before_action :set_sala, only: [:show, :edit, :update, :destroy]

  # GET /salas
  # GET /salas.json
  def index
    @salas = Sala.all
  end

  # GET /salas/1
  # GET /salas/1.json
  def show
  end

  # GET /salas/new
  def new
    @sala = Sala.new
  end

  # GET /salas/1/edit
  def edit
  end

  # POST /salas
  # POST /salas.json
  def create
    @sala = Sala.new(sala_params)

    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Sala was successfully created.' }
        format.json { render :show, status: :created, location: @sala }
      else
        format.html { render :new }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salas/1
  # PATCH/PUT /salas/1.json
  def update
    respond_to do |format|
      if @sala.update(sala_params)
        format.html { redirect_to @sala, notice: 'Sala was successfully updated.' }
        format.json { render :show, status: :ok, location: @sala }
      else
        format.html { render :edit }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy
    @sala.destroy
    respond_to do |format|
      format.html { redirect_to salas_url, notice: 'Sala was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sala
      @sala = Sala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sala_params
      params.require(:sala).permit(:edificio, :piso, :nro_sala, :capacidad, :tipo)
    end
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/salas/_form.html.erb
<%= form_with(model: sala, local: true) do |form| %>
  <% if sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sala.errors.count, "error") %> prohibited this sala from being saved:</h2>

      <ul>
      <% sala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :edificio %>
    <%= form.text_field :edificio %>
  </div>

  <div class="field">
    <%= form.label :piso %>
    <%= form.number_field :piso %>
  </div>

  <div class="field">
    <%= form.label :nro_sala %>
    <%= form.number_field :nro_sala %>
  </div>

  <div class="field">
    <%= form.label :capacidad %>
    <%= form.number_field :capacidad %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salas/edit.html.erb
<h1>Editing Sala</h1>

<%= render 'form', sala: @sala %>

<%= link_to 'Show', @sala %> |
<%= link_to 'Back', salas_path %>

app/views/salas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salas</h1>

<table>
  <thead>
    <tr>
      <th>Edificio</th>
      <th>Piso</th>
      <th>Nro sala</th>
      <th>Capacidad</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.edificio %></td>
        <td><%= sala.piso %></td>
        <td><%= sala.nro_sala %></td>
        <td><%= sala.capacidad %></td>
        <td><%= sala.tipo %></td>
        <td><%= link_to 'Show', sala %></td>
        <td><%= link_to 'Edit', edit_sala_path(sala) %></td>
        <td><%= link_to 'Destroy', sala, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sala', new_sala_path %>

app/views/salas/new.html.erb
<h1>New Sala</h1>

<%= render 'form', sala: @sala %>

<%= link_to 'Back', salas_path %>

app/views/salas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edificio:</strong>
  <%= @sala.edificio %>
</p>

<p>
  <strong>Piso:</strong>
  <%= @sala.piso %>
</p>

<p>
  <strong>Nro sala:</strong>
  <%= @sala.nro_sala %>
</p>

<p>
  <strong>Capacidad:</strong>
  <%= @sala.capacidad %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @sala.tipo %>
</p>

<%= link_to 'Edit', edit_sala_path(@sala) %> |
<%= link_to 'Back', salas_path %>